name: skripskuy_web
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: 4.6.1
  get_cli: ^1.7.1
  cupertino_icons: ^1.0.2
  firebase_auth: 3.3.14
  cloud_firestore: 3.1.12
  firebase_core: 1.14.1
  firebase_messaging: ^11.4.1
  shared_preferences: 2.0.11
  get_storage: ^2.0.3
  cached_network_image: 3.1.0+1
  lottie: 1.3.0
  auto_size_text: 3.0.0
  font_awesome_flutter: 8.11.0
  google_fonts: 2.2.0
  easy_debounce: 2.0.1
  intl: 0.17.0
  page_transition: 2.0.4
  smooth_page_indicator: 1.0.0+2
  table_calendar: 2.3.3
  flutter_rating_bar: 4.0.0
  introduction_screen: 3.0.2
  sizer: 2.0.15
  firebase_analytics: ^9.1.9
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lotties/
    - assets/icons/
    - assets/images/
