# Generated by Django 4.0.4 on 2022-08-13 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.PositiveIntegerField(blank=True, choices=[(0, 'Semua'), (1, 'Motor'), (2, 'Mobil')], default=0, null=True)),
                ('index', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('plate_number', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('order_status', models.PositiveIntegerField(blank=True, choices=[(0, 'Belum Dikerjakan'), (1, 'Sedang Dikerjakan'), (2, 'Selesai'), (3, 'Dibatalkan'), (4, 'Dibayar')], default=0, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('address', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('vehicle_type', models.PositiveIntegerField(blank=True, choices=[(0, 'Semua'), (1, 'Motor'), (2, 'Mobil')], default=0, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('is_open', models.BooleanField(blank=True, default=False, null=True)),
                ('open_hour', models.TimeField(blank=True, null=True)),
                ('close_hour', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('firebase_id', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('firebase_token', models.CharField(blank=True, max_length=255, null=True)),
                ('user_role', models.PositiveIntegerField(blank=True, choices=[(0, 'Admin'), (1, 'User'), (2, 'Service Provider')], default=1, null=True)),
                ('url_photo', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('full_name', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('type', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('cost', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookqueue.service')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookqueue.user'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('rating', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookqueue.order')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookqueue.service')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookqueue.user')),
            ],
        ),
        migrations.CreateModel(
            name='OrderQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('index', models.PositiveIntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookqueue.service')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookqueue.order')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('cost', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookqueue.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookqueue.service'),
        ),
        migrations.AddField(
            model_name='order',
            name='service_package',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookqueue.servicepackage'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookqueue.user'),
        ),
        migrations.CreateModel(
            name='OperationalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(blank=True, default=False, null=True)),
                ('day', models.PositiveIntegerField(blank=True, choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Minggu')], default=0, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookqueue.service')),
            ],
            options={
                'unique_together': {('service', 'day')},
            },
        ),
    ]
